name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libcmocka-dev valgrind

    - name: Build project
      run: make

    - name: Run tests
      run: make test

    - name: Run tests with Valgrind
      run: make valgrind
